/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RunwayRouteImport } from './routes/runway'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'

const RunwayRoute = RunwayRouteImport.update({
  id: '/runway',
  path: '/runway',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CollectionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/runway': typeof RunwayRoute
  '/collections/$slug': typeof CollectionsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/runway': typeof RunwayRoute
  '/collections/$slug': typeof CollectionsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/runway': typeof RunwayRoute
  '/collections/$slug': typeof CollectionsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/collections'
    | '/contact'
    | '/runway'
    | '/collections/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/collections'
    | '/contact'
    | '/runway'
    | '/collections/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/collections'
    | '/contact'
    | '/runway'
    | '/collections/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CollectionsRoute: typeof CollectionsRouteWithChildren
  ContactRoute: typeof ContactRoute
  RunwayRoute: typeof RunwayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/runway': {
      id: '/runway'
      path: '/runway'
      fullPath: '/runway'
      preLoaderRoute: typeof RunwayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof CollectionsRoute
    }
  }
}

interface CollectionsRouteChildren {
  CollectionsSlugRoute: typeof CollectionsSlugRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsSlugRoute: CollectionsSlugRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CollectionsRoute: CollectionsRouteWithChildren,
  ContactRoute: ContactRoute,
  RunwayRoute: RunwayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
